query TestDoc($id: ID!, $page: Int, $perPage: Int) {
  testDoc(id: $id) {
    id
    path
    title
    belongsTo(page: $page, perPage: $perPage) @paginate {
      pageInfo {
        totalPages
        currentPage
      }
      edges {
        node {
          ... on TestDoc {
            id
            path
            title
          }
        }
      }
    }
  }
}
