name: Lint

on:
  push:
    branches:
      - master
    paths:
      - '**.js'
      - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.js'
      - '.github/workflows/lint.yml'

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6.31.0

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install -no-frozen-lockfile

      - name: Run linter
        run: pnpm run lint
