name: Lint

on:
  push:
    branches:
      - master
    paths:
      - '**.js'
      - '.github/workflows/lint.yml'
  pull_request:
    branches:
      - master
    paths:
      - '**.js'
      - '.github/workflows/lint.yml'

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run linter
        run: yarn lint
