name: Test

on:
  push:
    branches:
      - master
    paths:
      - 'pnpm-lock.yaml'
      - 'jest.config.js'
      - 'gridsome/**/*.js'
      - 'packages/**/*.js'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'pnpm-lock.yaml'
      - 'jest.config.js'
      - 'gridsome/**/*.js'
      - 'packages/**/*.js'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['12', '14', '16']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.20.3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test:unit -- --ci
