name: Test

on:
  push:
    branches:
      - master
    paths:
      - 'yarn.lock'
      - 'jest.config.js'
      - 'gridsome/**/*.js'
      - 'packages/**/*.js'
      - '.github/workflows/test.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'yarn.lock'
      - 'jest.config.js'
      - 'gridsome/**/*.js'
      - 'packages/**/*.js'
      - '.github/workflows/test.yml'

jobs:
  test:
    name: Node.js ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: ['12', '14', '16']
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ runner.node-version }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test:unit --ci
